export const SHOW_DISCOVERY_NOTIFICATION = 'SHOW_DISCOVERY_NOTIFICATION';
export const HIDE_DISCOVERY_NOTIFICATION = 'HIDE_DISCOVERY_NOTIFICATION';
export const DISCOVERY_NOTSET_NOTIFICATION = 'DISCOVERY_NOTSET_NOTIFICATION';

